name: Continuous Integration Workflow

# This workflow is triggered whenever a new PR is created on the main branch
on:
  pull_request:
    branches:
      - main
    # paths:
    #   - 'web/**'
  push:
    branches:
      - main
    # paths:
    #   - 'web/**'

jobs:

  # Run unit tests to make sure everything is 👍
  build:
    name: 'Run Build'
    defaults:
      run:
        shell: bash
        # Define the working directory for all run steps in the workflow
        # working-directory: ./web
    # Specify the OS we want the workflow to run on
    runs-on: ubuntu-22.04
    # Define the steps for this job
    steps:
    - uses: actions/checkout@v4
      name: 'Checkout repository'

    - name: 'Install Java'
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify

